image: node:12.20.1

matrix:
  - env: COMMAND=build

install:
  - npm install

script:
  - if [[ "$COMMAND" ]]; then npm run $COMMAND; fi

deploy:
  - npm install -g serve
  - npm install -g pm2
  - pm2 start npm -- start

cache:
  - node_modules