kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
- name: testing
  image: node:12.20.1
  pull: "if-not-exists"
  commands:
  - npm install
  - npm test

- name: building
  image: node:12.20.1
  pull: "if-not-exists"
  commands:
  - npm install
  - npm run build

trigger:
  event:
  - push
  - pull_request
  branch:
  - master

---
kind: pipeline
type: ssh
name: default-deploy

server:
  host: 167.71.247.201
  user: root
  password:
    from_secret: ssh_password

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
- name: server
  commands:
  - npm install -g serve

- name: server
  commands:
  - npm install
  - npm run build

- name: deploy
  commands:
  - cd ./build/
  - serve

trigger:
  event:
  - push
  - pull_request
  branch:
  - master
depends_on:
- testing
- building
