kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: testing
  image: node:12.20.1
  pull: true
  commands:
  - npm install
  - npm test

steps:
- name: building
  image: node:12.20.1
  pull: true
  settings:
    token:
      from_secret: test_token
  commands:
  - npm install
  - npm run build
  - echo $token

steps:
- name: deploy
  image: appleboy/drone-ssh
    settings:
    host: 167.71.247.201
    username: root
    password:
      from_secret: ssh_password
    port: 22
    script:
      - npm install -g serve
      - cd ./build/
      - serve

trigger:
  event:
  - push
  - pull_request
  branch:
  - master

--
kind: pipeline
type: ssh
name: default-deploy

server:
  host: 167.71.247.201
  user: root
  password:
    from_secret: ssh_password

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
- name: server
  commands:
  - npm install -g serve

steps:
- name: server
  commands:
  - npm install
  - npm run build

steps:
- name: deploy
  commands:
  - cd ./build/
  - serve

trigger:
  event:
  - push
  - pull_request
  branch:
  - master
depends_on:
- testing
- building
